<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE orthography [
  <!ELEMENT orthography (alphabet, srrules?, rules)>
  <!ATTLIST orthography lang (Tr-TR | Tk-TK | Az-AZ) #REQUIRED>

  <!ELEMENT alphabet (consonants, vowels)>

  <!ELEMENT consonants (#PCDATA)>

  <!ELEMENT vowels (#PCDATA)>

  <!ELEMENT srrules (srrule)*>
  <!ELEMENT srrule EMPTY>
  <!ATTLIST srrule
    old CDATA #REQUIRED
    new CDATA #REQUIRED>

  <!ELEMENT rules (rule)+>

  <!ELEMENT rule (description, transformation*)>
  <!ATTLIST rule
  id CDATA #REQUIRED
  phase ( 1 | 2 | 3 | 4 | 5 ) #REQUIRED>
  <!ELEMENT description (#PCDATA)>

  <!ELEMENT transformation (conditions?)>
  <!ATTLIST transformation 

  morpheme ( Previous | This | Next ) #REQUIRED
    
  action (
  Append |
  Prepend |
  DeleteSurface |
  DeleteFirstLetter |
  DeleteFirstVowel | 
  DeleteLastLetter | 
  DeleteLastVowel |
  DoubleLastLetter | 
  Replace |
  LexicalToSurface 
  ) #REQUIRED  
  operandOne CDATA #IMPLIED
  operandTwo CDATA #IMPLIED
  flag CDATA #IMPLIED>

  <!ELEMENT conditions (condition+)>
  <!ATTLIST conditions
  flag ( And | Or ) #REQUIRED>

  <!ELEMENT condition EMPTY>
  <!ATTLIST condition 
  morpheme ( Previous | This | Next ) #REQUIRED
  operator (
  EndsWithConsonant |
  EndsWithVowel |
  FirstLetterEquals |
  LastLetterEquals |
  LastVowelEquals |
  MorphemeEquals |
  MorphemeNotEquals |
  HasFlags |
  HasNotFlags |
  PenultVowelEquals |
  StartsWithConsonant |
  StartsWithVowel | 
  IsLastMorpheme |
  IsFirstMorpheme |
  IsNotLastMorpheme |
  IsNotFirstMorpheme
    
  ) #REQUIRED
  operand CDATA #IMPLIED>]>

<orthography lang="Tr-TR">

  <alphabet>
    <consonants>bcçdfgğhjklmnprsştvyýzDCSKYÇP</consonants>
    <vowels>áaâeéıîioóöúûuüUAI</vowels>
  </alphabet>

  <srrules>
    <!--<srrule old="aa" new="bb"/>-->
  </srrules>

  <!-- operandOne ve operandTwo string tipinde -->

  <rules>

    <rule id="DUSME_UNLU" phase="2">
      <description>Önce gelen ek ünlü ile bitiyorsa bu ekin başındaki ünlüyü düşür</description>
      <transformation morpheme="This" action="DeleteFirstLetter">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="EndsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="DUSME_UNSUZ" phase="2">
      <description>Önceki ek ünsüz ile bitiyorsa bu ekin başındaki ünsüzü (kaynaştırma) düşür</description>
      <transformation morpheme="This" action="DeleteFirstLetter">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="EndsWithConsonant" />
        </conditions>
      </transformation>
    </rule>

    <rule id="DONUSUM_D" phase="2">
      <description>Önceki ek sert sessiz ile bitirosa D => t değilse D => d</description>
      <transformation morpheme="This" action="Replace" operandOne="D" operandTwo="t" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastLetterEquals" operand="pçtkşsfh" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="D" operandTwo="d" flag="all" />
    </rule>

    <rule id="DONUSUM_C" phase="2">
      <description>Önceki ek sert sessiz ile bitirosa C => ç değilse c </description>
      <transformation morpheme="This" action="Replace" operandOne="C" operandTwo="ç" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastLetterEquals" operand="pçtkşsfh" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="C" operandTwo="c" flag="all" />
    </rule>

    <rule id="DONUSUM_A" phase="2">
      <description>Önceki ekin son sesli harfi kalın ise A => a değilse A => e </description>
      <transformation morpheme="This" action="Replace" operandOne="A" operandTwo="a" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastVowelEquals" operand="aıouâû" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="A" operandTwo="e" flag="all" />
    </rule>

    <rule id="DONUSUM_I" phase="2">
      <description>Önceki ekin son sesli harfi kalın ise I => ı değilse I => i </description>
      <transformation morpheme="This" action="Replace" operandOne="I" operandTwo="ı" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastVowelEquals" operand="aıouâû" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="I" operandTwo="i" flag="all" />
    </rule>

    <rule id="DONUSUM_U" phase="2">
      <description>Önceki ekin son sesli harfine göre  U => ı, i, u veya ü olur </description>
      <transformation morpheme="This" action="Replace" operandOne="U" operandTwo="ı" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastVowelEquals" operand="aıâ" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="U" operandTwo="i" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastVowelEquals" operand="eiéáî" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="U" operandTwo="u" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastVowelEquals" operand="ouû" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="U" operandTwo="ü" flag="all" />
    </rule>

    <rule id="YUMUSAMA_pb" phase="3">
      <description>	Sonraki ek ünlü ile başlıyorsa sondaki p => b'ye yumuşar </description>
      <transformation morpheme="This" action="Replace" operandOne="p" operandTwo="b" flag="last">
        <conditions flag="Or">
          <condition morpheme="Next" operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="YUMUSAMA_çc" phase="3">
      <description> Sonraki ek ünlü ile başlıyorsa sondaki ç => c'ye yumuşar </description>
      <transformation morpheme="This" action="Replace" operandOne="ç" operandTwo="c" flag="last">
        <conditions flag="Or">
          <condition morpheme="Next" operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="YUMUSAMA_td" phase="3">
      <description>	Sonraki ek ünlü ile başlıyorsa sondaki t => d'ye yumuşar 	</description>
      <transformation morpheme="This" action="Replace" operandOne="t" operandTwo="d" flag="last">
        <conditions flag="Or">
          <condition morpheme="Next" operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="YUMUSAMA_kğ" phase="3">
      <description>	Sonraki ek ünlü ile başlıyorsa sondaki k => ğ'ye yumuşar 	</description>
      <transformation morpheme="This" action="Replace" operandOne="k" operandTwo="ğ" flag="last">
        <conditions flag="Or">
          <condition morpheme="Next" operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="YUMUSAMA_kg" phase="3">
      <description> Sonraki ek ünlü ile başlıyorsa sondaki k => g'ye yumuşar. çelenk => çelengi </description>
      <transformation morpheme="This" action="Replace" operandOne="k" operandTwo="g" flag="last">
        <conditions flag="Or">
          <condition morpheme="Next" operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="YUMUSAMA_gğ" phase="3">
      <description>	Sonraki ek ünlü ile başlıyorsa sondaki g => ğ'ye yumuşar. psikolog =› psikoloğa	</description>
      <transformation morpheme="This" action="Replace" operandOne="g" operandTwo="ğ" flag="last">
        <conditions flag="Or">
          <condition morpheme="Next" operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="DUSME_SON_UNLU" phase="3">
      <description>
        Gelen ek ünlü ile başlıyorsa son sesli harf düşer.
        ağız =› ağz-a, burun =› burn-um, zehir =› zehr-e
        Ancak ben ağızım ve biz ağızız şeklinde 1. tekil ve çoğul şahıs ekleri geldiğinde bu düşme olmaz.
      </description>
      <transformation morpheme="This" action="DeleteLastVowel">
        <conditions flag="And">
          <condition morpheme="Next" operator="StartsWithVowel" />
          <condition morpheme="Next" operator="MorphemeNotEquals" operand="EKFIIL_SAHIS_BEN_(y)Um" />
          <condition morpheme="Next" operator="MorphemeNotEquals" operand="EKFIIL_SAHIS_BIZ_(y)Uz" />
        </conditions>
      </transformation>
    </rule>

    <rule id="DUSME_SON_UNLU_EDILGEN" phase="3">
      <description>
        Edilgen eki geldiğinde son ünlünün düşmesi kuralı
        kavur => kavrul
        doğur => doğrul
      </description>
      <transformation morpheme="This" action="DeleteLastVowel">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="FY_EDILGEN_Ul_(U)n" />
        </conditions>
      </transformation>
    </rule>

    <rule id="CIFTLESME_SON_UNSUZ" phase="3">
      <description>
        hat›hatt-ı, ret›redd-i , serhat›serhadd-i
      </description>
      <transformation morpheme="This" action="DoubleLastLetter">
        <conditions flag="Or">
          <condition morpheme="Next" operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_su" phase="1">
      <description>
        Gelen ek sesli ile başlıyorsa veya IC_SAHIPLIK_O_(s)U, IC_HAL_ILGI_(n)Un eklerinden biri ise
        sona y karakteri ekle
      </description>
      <transformation morpheme="This" action="Append" operandOne="y">
        <conditions flag="Or">
          <condition morpheme="Next" operator="StartsWithVowel" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_SAHIPLIK_O_(s)U" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_ILGI_(n)Un" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_N" phase="1">
      <description>
        Bazı ek ve kelimelerden sonra araya n sesinin girmesi. kapısıya => kapısına
        kendice => kendince
      </description>
      <transformation morpheme="This" action="Append" operandOne="n">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_YONELME_(y)A" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_BULUNMA_DA" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_AYRILMA_DAn" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_BELIRTME_(y)U" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IY_ZARF_CA" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_o" phase="1">
      <description> o, bu, şu kökleri bazı ekler için araya n sesi alırlar </description>
      <transformation morpheme="This" action="Append" operandOne="n">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="ZAMIR_COGUL_lAr" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_YONELME_(y)A" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_BULUNMA_DA" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_AYRILMA_DAn" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_BELIRTME_(y)U" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IY_SIFAT_sUz" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IY_SIFAT_lU" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IY_ISIM_lUK" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IY_ISIM_cAğIz" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="IY_ZARF_CA" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_bana" phase="1">
      <description>
        Gelen ek yönelme hal eki ise e => a olur.
        ben => bana, sen => sana
      </description>
      <transformation morpheme="This" action="Replace" operandOne="e" operandTwo="a" flag="first">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_YONELME_(y)A" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_benim" phase="1">
      <description>
        ilgi hali, im şeklini alır. benim, bizim
      </description>
      <transformation morpheme="Next" action="Replace" operandOne="nUn" operandTwo="nim" flag="first">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_HAL_ILGI_(n)Un" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_INCELME_A" phase="5">
      <description>	saat => saate özel durumu için yerleştirilen á karakteri sonradan a olur. </description>
      <transformation morpheme="This" action="Replace" operandOne="á" operandTwo="a" flag="all" />
    </rule>

    <rule id="INCELME_SAPKA_A" phase="5">
      <description>yâr -> yâre özel durumu için yerleştirilen á karakteri sonradan â olur.</description>
      <transformation morpheme="This" action="Replace" operandOne="á" operandTwo="â" flag="all" />
    </rule>

    <rule id="OZEL_INCELME_O" phase="5">
      <description> gol-e, alkol-lü özel durumu için yerleştirilen ó karakteri sonradan o olur. </description>
      <transformation morpheme="This" action="Replace" operandOne="ó" operandTwo="o" flag="all" />
    </rule>

    <rule id="OZEL_INCELME_U" phase="5">
      <description> ampul-e özel durumu için yerleştirilen ú karakteri sonradan o olur. </description>
      <transformation morpheme="This" action="Replace" operandOne="ú" operandTwo="u" flag="all" />
    </rule>


    <rule id="OZEL_BIZ_lIm" phase="2">
      <description>
        Önceki ek istek eki ise k olan yüzey lIm olarak değişir.
        gelek => gelelim
      </description>
      <transformation morpheme="This" action="Replace" operandOne="k" operandTwo="lIm" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="MorphemeEquals" operand="FC_KIP_ISTEK_(y)A" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_UYOR" phase="2">
      <description>
        Önceki ekin son harfi a veya e ise bu harfi sil.
        Yok eğer Son harf ı,i,u,ü ise kendi ilk harfini (U) sil
      </description>
      <transformation morpheme="Previous" action="DeleteLastLetter">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastLetterEquals" operand="ae" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="DeleteFirstLetter">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastLetterEquals" operand="ıiuü" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_de" phase="3">
      <description>
        de fiili bazı eklerden sonra di halini alyor.
        de => di-yecek ama de-yip and de-yince
        Şimdiki zaman eki L_OZEL_UYOR kuralı de => d yaptığından üyor => iyor olur.
      </description>
      <transformation morpheme="Next" action="Replace" operandOne="ü" operandTwo="i" flag="first">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="FC_ZAMAN_SIMDIKI_(U)yor" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="e" operandTwo="i" flag="first">
        <conditions flag="And">
          <condition morpheme="Next" operator="MorphemeNotEquals" operand="FIILIMSI_ZARF_(y)Up" />
          <condition morpheme="Next" operator="MorphemeNotEquals" operand="FIILIMSI_ZARF_(y)UncA" />
          <condition morpheme="Next" operator="MorphemeNotEquals" operand="FIILIMSI_ISIM_(y)Uş" />
          <condition morpheme="Next" operator="MorphemeNotEquals" operand="FY_TANIMLAMA_(y)UcU" />
          <condition morpheme="Next" operator="MorphemeNotEquals" operand="FC_YF_TEZLIK_(y)Uver" />
          <condition morpheme="Next" operator="FirstLetterEquals" operand="y" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_ye" phase="3">
      <description>
        ye fiili bazı eklerden sonra yi halini alyor.
        ye => yi-yecek, yi-yip and yi-yince
        Şimdiki zaman eki L_OZEL_UYOR kuralı ye => y yaptığından üyor => iyor olur.
      </description>
      <transformation morpheme="This" action="Replace" operandOne="e" operandTwo="i" flag="last">
        <conditions flag="Or">
          <condition morpheme="Next" operator="FirstLetterEquals" operand="y" />
        </conditions>
      </transformation>
      <transformation morpheme="Next" action="Replace" operandOne="ü" operandTwo="i" flag="first">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="FC_ZAMAN_SIMDIKI_(U)yor" />
        </conditions>
      </transformation>
    </rule>

    <!-- Bu 2 kural geniş zaman eki için -->

    <rule id="GZ_OLUMSUZ" phase="2">
      <description> Olumsuzluk ekinden sonra gelen geniş zaman ekinden sonra 1. tekil şahıs eki geliyorsa, geniş
      zaman ekinin yüzeyi düşer</description>
      <transformation morpheme="This" action="DeleteSurface">
        <conditions flag="And">
          <condition morpheme="Previous" operator="MorphemeEquals" operand="FY_OLUMSUZLUK_mA" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="EKFIIL_SAHIS_BEN_(y)Um" />
        </conditions>
      </transformation>      
    </rule>
      

    <rule id="OZEL_GZ" phase="2">
      <description>
        Genis zaman ekinden önce gelen morfemde (fiilde) S_OZEL_GZ kuralı var ise Ur => Ar olur.
        Önceki ek olumsuzluk eki ise Ur => z olur.
      </description>
      <transformation morpheme="Next" action="Replace" operandOne="yUm" operandTwo="m" flag="all">
        <conditions flag="And">
          <condition morpheme="Previous" operator="MorphemeEquals" operand="FY_OLUMSUZLUK_mA" />
          <condition morpheme="Next" operator="MorphemeEquals" operand="EKFIIL_SAHIS_BEN_(y)Um" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="U" operandTwo="A" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="HasFlags" operand="genis_Ar" />
        </conditions>
      </transformation>      
      <transformation morpheme="This" action="Replace" operandOne="Ur" operandTwo="z" flag="all">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="MorphemeEquals" operand="FY_OLUMSUZLUK_mA" />
          <condition morpheme="Previous" operator="MorphemeEquals" operand="FC_YF_YETERSIZLIK_(y)AmA" />
        </conditions>
      </transformation>
    </rule>
    <rule id="DUSME_UNLU_GZ" phase="2">
      <description>yapar, eder </description>
      <transformation morpheme="This" action="DeleteFirstVowel">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="EndsWithVowel" />
        </conditions>
      </transformation>
    </rule>


    <rule id="OZEL_EDILGEN" phase="2">
      <description>     </description>
      <transformation morpheme="This" action="Replace" operandOne="l" operandTwo="n" flag="last">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="EndsWithVowel" />
          <condition morpheme="Previous" operator="LastLetterEquals" operand="l" />
        </conditions>
      </transformation>
    </rule>


    <rule id="OZEL_ETTIRGEN" phase="2">
      <description>     </description>
      <transformation morpheme="This" action="Replace" operandOne="DUr" operandTwo="t" flag="first">
        <conditions flag="And">
          <condition morpheme="Previous" operator="EndsWithVowel" />
          <condition morpheme="Previous" operator="HasNotFlags" operand="ettirgen_dur" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="DUr" operandTwo="t" flag="first">
        <conditions flag="And">
          <condition morpheme="Previous" operator="HasFlags" operand="ettirgen_t" />
        </conditions>
      </transformation>
      <transformation morpheme="This" action="Replace" operandOne="DUr" operandTwo="Ut" flag="first">
        <conditions flag="And">
          <condition morpheme="Previous" operator="HasFlags" operand="ettirgen_ut" />
        </conditions>
      </transformation>
    </rule>

    <rule id="TAMLAMA_OZEL" phase="4">
      <description>zeytinyağ -> zeytinyağı </description>
      <transformation morpheme="This" action="Append" operandOne="_">
        <conditions flag="Or">
          <condition morpheme="This" operator="IsLastMorpheme" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OZEL_ETTIRTGEN" phase="2">
      <description>     </description>
      <transformation morpheme="This" action="Replace" operandOne="t" operandTwo="DUr" flag="first">
        <conditions flag="Or">
          <condition morpheme="Previous" operator="LastLetterEquals" operand="t" />
        </conditions>
      </transformation>
    </rule>


    <rule id="SAPKA_DUSUR_A" phase="5">
      <description>kâr -> kar </description>
      <transformation morpheme="This" action="Replace" operandOne="â" operandTwo="a" flag="all" />
    </rule>

    <rule id="SAPKA_DUSUR_I" phase="5">
      <description>kâr -> kar </description>
      <transformation morpheme="This" action="Replace" operandOne="î" operandTwo="i" flag="all" />
    </rule>

    <rule id="SAPKA_DUSUR_U" phase="5">
      <description>kâr -> kar </description>
      <transformation morpheme="This" action="Replace" operandOne="û" operandTwo="u" flag="all" />
    </rule>

    <rule id="OZEL_EKFIIL" phase="3">
      <description>
        Sondaki özel ý karakteri ekfiil zaman ekleri geldiğinde düşer.
        ekfiil olan i tekbaşına bulunamayacağından, aksi takdirde düşmez.
      </description>
      <transformation morpheme="This" action="DeleteLastLetter" />
    </rule>

    <rule id="OZEL_KUCULTME" phase="1">
      <description>
        Eğer gelen ek küçültme eki olan CUK ise sondaki k'yı düşür. küçük + cük => küçücük
      </description>
      <transformation morpheme="This" action="DeleteLastLetter">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="IY_ISIM_KUCULTME_CUK" />
        </conditions>
      </transformation>
    </rule>

    <rule id="ZAMAN_kü" phase="1">
      <description>
        Yalnızca dün, gün ve bugün kelimelerinden sonra ki eki kü halini alır
      </description>
      <transformation morpheme="Next" action="Replace" operandOne="i" operandTwo="ü" flag="first">
        <conditions flag="Or">
          <condition morpheme="Next" operator="MorphemeEquals" operand="IC_AITLIK_ki" />
        </conditions>
      </transformation>
    </rule>

    <rule id="OKUNUSDAN_YAZILISA" phase="5">
      <description>
        Alıntı ve kısaltma türündeki kelimelerin okunuşu olan lexical biçimini
      </description>
      <transformation morpheme="This" action="LexicalToSurface" />
    </rule>

    <rule id="KESME_KALDIR" phase="1">
      <description>
        Üretimin başında kesme işareti yokmuş gibi hareket edilir.
      </description>
      <transformation morpheme="This" action="DeleteFirstLetter" />
    </rule>

    <rule id="KESME_EKLE" phase="5">
      <description>
        Üretimin sonunda kesme işareti olması gereken yere eklenir.
      </description>
      <transformation morpheme="This" action="Append" operandOne="'" />
    </rule>

    <rule id="ALTTIRE_KALDIR" phase="5">
      <description>
        Alıntı ve kısaltma türündeki kelimelerin okunuşu olan lexical biçimini
      </description>
      <transformation morpheme="This" action="Replace" operandOne="_" operandTwo=" " flag="all" />
    </rule>

    <rule id="DROP_ID_DIGIT" phase="1">
      <description> Remove the numeric character at the end of the lexical form </description>
      <transformation morpheme="This" action="DeleteLastLetter" />
    </rule>

  </rules>
</orthography>